version: "1.0"
engine:
  type: "duckdb"
pipeline:
  state_file: "pipeline_state.json"
tables:
  - name: "customers"
    rules:
      - name: "id_check"
        rule_type: "completeness"
        column: "customer_id"
        severity: "error"
  - name: "orders"
    rules:
      - name: "id_check"
        rule_type: "completeness"
        column: "order_id"
        severity: "error"
